stages:
  - linting
  - build_and_test

variables:
  ROS_DISTRO: jazzy

linting:
  stage: linting
  image: $CI_REGISTRY/hector/workspace/docker_workspace:dev-amd64
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - sudo apt-get update && sudo apt-get install -y clang-format cppcheck libxml2-utils black git pre-commit
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - rosdep update --rosdistro ${ROS_DISTRO}
  script:
    - echo "Running pre-commit hooks..."
    - pre-commit run --all-files


build-and-test:
  stage: build_and_test
  image: $CI_REGISTRY/hector/workspace/docker_workspace:dev-amd64
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions python3-rosdep
    - rosdep update --rosdistro ${ROS_DISTRO}
  script:
    - echo "Installing dependencies..."
    - rosdep install --from-paths . --ignore-src -r -y
    - source /opt/ros/${ROS_DISTRO}/setup.bash && source /opt/hector/${ROS_DISTRO}/setup.bash
    - echo "Building packages..."
    - colcon build
    - echo "Running tests..."
    - colcon test  || FAILED=1
    - colcon test-result --verbose
    - if [ $FAILED ]; then exit 1; fi
  needs:
    - linting
